# Generated by Django 5.0.3 on 2024-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assure',
            name='numr_tlfn_autre_assure',
            field=models.IntegerField(default=0),
        ),
    ]
