# Generated by Django 5.0.3 on 2024-04-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_accident_date_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/degat_photos/'),
        ),
    ]
